"""currency_converter_db

Revision ID: bf5e2f5496d4
Revises: 
Create Date: 2023-04-27 04:58:53.263762

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'bf5e2f5496d4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('currency',
                    sa.Column('name', sa.String(), nullable=True),
                    sa.Column('code', sa.String(), nullable=False),
                    sa.Column('rates', sa.JSON(), nullable=False),
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.PrimaryKeyConstraint('code', 'id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('currency')
    # ### end Alembic commands ###
